# Site settings
title: Abstract This!
email: your-email@domain.com
description: "todo"
baseurl: ""
url: "http://www.abstractthis.com"
timezone: Pacific/Honolulu

# Site assets & libraries
jquery: 1.11.1
modernizr: 2.6.2
bootstrap: 3.2.0

# Collections
collections:
  members:
    output: true
    permalink: /members/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown: kramdown
permalink: pretty

# Misc site vars
facebook: todo
meetup: todo
googleplus: todo
twitter: todo
github: https://github.com/abstractthis

# API Keys
key_gmap: todo